// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

namespace KerraGameplayTags
{
	/* Input Tags */
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Sword);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Sword);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Roll);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_SwitchTarget);
	
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_MustBeHeld_Block);

	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Toggleable_TargetLock);

	/* Player Tag */
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Sword);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Sword);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Sword);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Sword);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Roll);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Block);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_TargetLock);

	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Sword);

	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Rolling);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_Blocking);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_TargetLock);
	
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);

	/* Player Event Tag */
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Sword);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Sword);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SuccessBlock);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Left);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_SwitchTarget_Right);

	/* Enemy Tag */
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);
	
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);
	
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Strafing);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_UnderAttack);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Status_Unblockable);

	/* Shared Tags */
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_SpawnProjectile);

	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);

	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);

	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Front);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Left);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Right);
	KERRA_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_HitReact_Back);
	
}
